name: Terraform Plan

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  detect:
    name: Detect stacks & environment
    runs-on: ubuntu-latest
    outputs:
      stacks: ${{ steps.stacks.outputs.stacks }}
      env: ${{ steps.env.outputs.env }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0    

      # ðŸ”¹ Detect environment from tfvars change
      - name: Detect environment
        id: env
        run: |
          ENV="dev"

          if [ "${{ github.event_name }}" = "pull_request" ]; then
            DIFF_RANGE="origin/${{ github.base_ref }}...HEAD"
          else
            if git rev-parse HEAD~1 >/dev/null 2>&1; then
              DIFF_RANGE="HEAD~1...HEAD"
            else
              DIFF_RANGE="HEAD"
            fi
          fi

          if git diff --name-only $DIFF_RANGE | grep -q "environments/prod.tfvars"; then
            ENV="prod"
          elif git diff --name-only $DIFF_RANGE | grep -q "environments/qa.tfvars"; then
            ENV="qa"
          fi

          echo "env=$ENV" >> $GITHUB_OUTPUT


      # ðŸ”¹ Detect ALL changed Terraform stacks
      - name: Detect Terraform stacks
        id: stacks
        run: |
          STACKS=()

          if [ "${{ github.event_name }}" = "pull_request" ]; then
            DIFF_RANGE="origin/${{ github.base_ref }}...HEAD"
          else
            if git rev-parse HEAD~1 >/dev/null 2>&1; then
              DIFF_RANGE="HEAD~1...HEAD"
            else
              DIFF_RANGE="HEAD"
            fi
          fi

          CHANGED_FILES=$(git diff --name-only $DIFF_RANGE)

          for dir in $(ls -d */); do
            dir=${dir%/}

            if [ "$dir" = "modules" ]; then
              continue
            fi

            if echo "$CHANGED_FILES" | grep -q "^$dir/"; then
              STACKS+=("\"$dir\"")
            fi
          done

          echo "stacks=[${STACKS[*]}]" >> $GITHUB_OUTPUT



  plan:
    name: Terraform Plan
    needs: detect
    if: needs.detect.outputs.stacks != '[]'

    strategy:
      matrix:
        stack: ${{ fromJson(needs.detect.outputs.stacks) }}

    uses: habibrmns/githubactions/.github/workflows/tf_plan.yaml@main
    with:
      stack: ${{ matrix.stack }}
      environment: ${{ needs.detect.outputs.env }}
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
